// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvS7E_hk9L2q-pmvJ-3PjiCEi5eIatSjg',
    appId: '1:175336461951:web:4c7020cb26aef1dde0914a',
    messagingSenderId: '175336461951',
    projectId: 'localiza-agendamentos',
    authDomain: 'localiza-agendamentos.firebaseapp.com',
    storageBucket: 'localiza-agendamentos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhnMdEJNGqFjgKfCtIMJl_2_AUIaFR42Y',
    appId: '1:175336461951:android:f8d3d8145c165361e0914a',
    messagingSenderId: '175336461951',
    projectId: 'localiza-agendamentos',
    storageBucket: 'localiza-agendamentos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSEXvgbm8j2F6PilQAcu9m0YzvLcIBxVw',
    appId: '1:175336461951:ios:fab565b49ed0315be0914a',
    messagingSenderId: '175336461951',
    projectId: 'localiza-agendamentos',
    storageBucket: 'localiza-agendamentos.firebasestorage.app',
    iosBundleId: 'com.example.localizaAgendamentos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSEXvgbm8j2F6PilQAcu9m0YzvLcIBxVw',
    appId: '1:175336461951:ios:fab565b49ed0315be0914a',
    messagingSenderId: '175336461951',
    projectId: 'localiza-agendamentos',
    storageBucket: 'localiza-agendamentos.firebasestorage.app',
    iosBundleId: 'com.example.localizaAgendamentos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvS7E_hk9L2q-pmvJ-3PjiCEi5eIatSjg',
    appId: '1:175336461951:web:8ecc7f9a8e027f25e0914a',
    messagingSenderId: '175336461951',
    projectId: 'localiza-agendamentos',
    authDomain: 'localiza-agendamentos.firebaseapp.com',
    storageBucket: 'localiza-agendamentos.firebasestorage.app',
  );
}
